### PR TITLE
fix(switch): disable focus and toggle when disabled

### LINKED ISSUE #307: switch: shows focus visual state even when disabled
### Expected behavior

Cannot be focused nor look like it when disabled

### Actual behavior

Can be, yo!

### Steps to repro

1. Disable and click.

### PR DESCRIPTION
**Pull request by danethurber**
fix #307

### CODE REVIEW

File: packages/switch/src/react/index.js [hunk 1]
```diff
@@ -116,6 +117,15 @@ class Switch extends React.Component {
   }
 }
 
+Switch.defaultProps = {
```
Comment (jaketrent) [inline packages/switch/src/react/index.js]: doesn't matter a bunch to me, but `defaultProps` have (probably) always come after `propTypes` in these components, at least the ones I just spot-checked.

Comment (danethurber) [reply packages/switch/src/react/index.js]: 👍 i'll move
