### PR TITLE
fix(actionmenu): remove useCloseOnDocumentEvents and stop using JSX p…

### LINKED ISSUE #1582: useCloseOnDocumentEvents buggy
Looks like the hook is invoking it's callback immediately now. Will debug and fix.

Slack: https://pluralsight.slack.com/archives/C70HPSJPP/p1611787899020600

### PR DESCRIPTION
**Pull request by EdwardIrby**
Resolves #1582

See Slack: https://pluralsight.slack.com/archives/C70HPSJPP/p1611787899020600

### CODE REVIEW

File: packages/actionmenu/src/react/index.tsx [hunk 1]
```diff
@@ -66,16 +66,8 @@ export const ActionMenu = React.forwardRef<HTMLUListElement, ActionMenuProps>(
       children,
       ...rest
     },
-    forwardedRef
+    ref
   ) => {
-    const ref = React.useRef<HTMLUListElement | null>(null)
```
Comment (jaketrent) [inline packages/actionmenu/src/react/index.tsx:71]: By removing this, we are removing the functionality to close the actionmenu by clicking outside of it.  That doesn't seem like a UX improvement. At the least it seems like it's a breaking change.

Why remove this entirely instead of changing away from the buggy implementation?

Comment (EdwardIrby) [reply packages/actionmenu/src/react/index.tsx:71]: Considered that actually but still couldn't get it to work because of Position not the hook. I could try and fix Position but that might cause unforeseen breakage. It's basically too coupled.

Comment (jaketrent) [reply packages/actionmenu/src/react/index.tsx:71]: I don't understand this answer.  Perhaps I need more info in order to:

How are Position and useCloseOnDocumentEvents too coupled?

And I don't understand the comment in standup:

Why does Position or ActionMenu need broken?  And what does broken mean?

**Comment by EdwardIrby** [comment]
It was react 17!!!!

https://reactjs.org/blog/2020/08/10/react-v17-rc.html#fixing-potential-issues

**Review by danethurber — APPROVED** [review]

**Review by jaketrent — COMMENTED** [review]
Awesome!  I'm glad you found the issue.
