### PR TITLE
Fix/text input icon alignment

### LINKED ISSUE #810: textinput: after field icon missaligned
the "after field w/ icon" story looks like the icon is aligned too far right

73007417-c0c3ce00-3dc9-11ea-920a-7ce7cd320bbd

### PR DESCRIPTION
**Pull request by EdwardIrby**
resolves #810

### CODE REVIEW

File: packages/icon/src/css/index.js [hunk 1]
```diff
@@ -25,7 +25,9 @@ export default {
     width: vars.widths.large
   },
   [`.psds-icon > svg`]: {
-    fill: 'currentColor'
+    fill: 'currentColor',
+    width: '100%',
+    height: '100%'
```
Comment (EdwardIrby) [inline packages/icon/src/css/index.js]: This is optional but I noticed icon wasn't aligning correctly in it's container. We can do this style or we can do the following

```
[`.psds-icon`]: {
    display: 'inline-flex',
   alignItems: 'center',
   justifyContent: 'center,
 }
```

**Comment by danethurber** [comment]
@EdwardIrby i spot checked a handful of components and they seemed to be ok

File: packages/textinput/src/css/index.js [hunk 2]
```diff
@@ -44,7 +44,7 @@ export default {
     padding: `6px ${layout.spacingXSmall}`
   },
   '.psds-text-input__field--w-after': {
-    paddingRight: 0
+    paddingRight: layout.spacingXSmall
```
Comment (jaketrent) [inline packages/textinput/src/css/index.js]: Kinda odd.  I wonder why we would have set this explicitly as 0.  Did that value work at some previous point?

File: packages/icon/src/css/index.js [hunk 3]
```diff
@@ -10,7 +10,14 @@ import * as vars from '../vars/index.js'
 
 export default {
   [`.psds-icon`]: {
-    display: 'inline-block'
+    display: 'inline-flex',
```
Comment (jaketrent) [inline packages/icon/src/css/index.js]: Not likely, but since Icon can take a child, is this layout change potentially breaking for any of those custom child cases?  (the ones that we don't have in our storybook to check)

Comment (EdwardIrby) [reply packages/icon/src/css/index.js]: Not that I can think of given Icon takes default size of medium
