### PR TITLE
fix(dropdown): set max height

### LINKED ISSUE #1300: fix(dropdown): dropdown menu closes on scroll
## Instructions

- open dropdown menu
- scroll a page 

### Expected behavior

Scroll doesn't affect dropdown menu behavior. 

### Actual behavior

Dropdown menu closes on scroll.

dropdown

### Related packages

- dropdown@9.0.5

### Environment

- OS - MacOS 10.12
- Browser version - Chrome v60

### PR DESCRIPTION
**Pull request by EdwardIrby**
resolve  #1300

### CODE REVIEW

File: packages/dropdown/src/css/index.ts [hunk 1]
```diff
@@ -169,7 +169,9 @@ export default {
   '.psds-dropdown__menu': {
     position: 'fixed',
     zIndex: 980,
-    marginTop: layout.spacingXXSmall
+    marginTop: layout.spacingXXSmall,
+    maxHeight: 400,
+    overflowY: 'scroll'
```
Comment (jaketrent) [inline packages/dropdown/src/css/index.ts:174]:
```suggestion
    overflowY: 'auto'
```

I'd suggest this change.  Works for scrolling when the max height is exceeded.  Looks nicer for the (hopefully) common case of no scroll.

What do you think?

**Review by jaketrent — CHANGES_REQUESTED** [review]

**Review by jaketrent — APPROVED** [review]
