### PR TITLE
fix(table): update column header click event arg order and aria-sort

### LINKED ISSUE #1024: Table: a11y columnheaders
the current column headers when rendered as a button fail a11y checks because a button can't have a role of columnheader

also. we should change the event argument order of the `onClick` prop so that the click event is the first argument

related thread -> https://pluralsight.slack.com/archives/C70HPSJPP/p1591279249202900

### PR DESCRIPTION
**Pull request by EdwardIrby**
resolves #1024

### CODE REVIEW

File: packages/table/src/react/index.js [hunk 1]
```diff
@@ -100,27 +110,44 @@ function ColumnHeader(props) {
...
-  return (
-    <Tag
-      role="columnheader"
-      {...styles.columnHeader(themeName, props, { active })}
-      {...filterReactProps(props, { tagName: Tag })}
-      onClick={handleClick}
-      style={style}
-      aria-sort={
+  const children = props.onClick ? (
+    <button {...styles.columnHeaderButton()} onClick={handleClick}>
```
Comment (EdwardIrby) [inline packages/table/src/react/index.js:119]: Not sure if we shouldn't just leave this on the TableColoumn header div

File: packages/table/src/react/index.js [hunk 2]
```diff
@@ -100,27 +110,44 @@ function ColumnHeader(props) {
...
+        {props.sort && getSortIcon(props)}
+      </div>
+    </button>
+  ) : (
+    <>
+      {props.children}
+      {props.sort && getSortIcon(props)}
+    </>
+  )
+  const sort = {
```
Comment (EdwardIrby) [inline packages/table/src/react/index.js:131]: Looked at dequeuniversity and they weren't event showing this attribute if it wasn't sorted. I went halfway and basically am not applying it unless the user has set sort of some sort on the column.

File: packages/table/src/react/index.js (hunk 1 above)
Comment (danethurber) [reply packages/table/src/react/index.js:119]: do you mean having the onClick event on the columnheader div. that seems fine to me
