### PR TITLE
fix(starrating): dont pass bright prop to dom button

### LINKED ISSUE #382: starrating: Intermittent Error
### Actual behavior
```
Warning: Received `false` for a non-boolean attribute `bright`.

If you want to write it to the DOM, pass a string instead: bright="false" or bright={value.toString()}.

If you used to conditionally omit it with bright={condition && value}, pass bright={condition ? value : undefined} instead.
   in span (created by Star)
   in Star (created by withTheme(Star))
   in withTheme(Star) (created by StarRating)
   in div (created by StarRating)
   in StarRating (created by withTheme(StarRating))
   in withTheme(StarRating)
   in div
   in Unknown (created by Styled(Component))
   in Styled(Component) (created by ProjectListItem)
   in span (created by index__MetadataDatum)
   in index__MetadataDatum (created by RowComponent)
   in div (created by index__Metadata)
   in index__Metadata (created by RowComponent)
   in div (created by index__Words)
   in index__Words (created by RowComponent)
   in div (created by index__Row)
   in index__Row (created by RowComponent)
   in RowComponent (created by ProjectListItem)
   in ProjectListItem
   in Unknown (created by Styled(Component))
   in Styled(Component)
   in div
   in section
   in Unknown (created by Styled(Component))
   in Styled(Component) (created by Home)
   in div (created by panel__Panel)
   in panel__Panel (created by PanelComponent)
   in PanelComponent (created by Home)
   in div (created by Home)
   in Home (created by Route)
   in Route (created by App)
   in Switch (created by App)
   in div (created by styled.div)
   in styled.div (created by App)
   in App
   in Router (created by BrowserRouter)
   in BrowserRouter
```
### Steps to repro

1. It's intermittent so not quite sure. 

### Related packages

- starrating@ ^1.2.0

### Environment

- OS - MacOS 10.13.6
- Browser version - Chrome v70.0.3538.110

### PR DESCRIPTION
**Pull request by jaketrent**
Fixes #382

### CODE REVIEW

File: packages/starrating/src/react/star.js [hunk 1]
```diff
@@ -101,8 +101,10 @@ class Star extends React.PureComponent {
     const {
       active,
       appearance,
+      bright,
       index,
       interactive,
+      onClick,
```
Comment (danethurber) [inline packages/starrating/src/react/star.js]: are you filtering onClick on purpose
