### PR TITLE
fix(dropdown): dev can set width thus truncating long input & options

### LINKED ISSUE #487: dropdown: Add max width restriction
## Enhancement Request
Please add the ability to restrict the width of the dropdown to a max width.

### Desired behavior
Any text that expends past the max width should be truncated.

Support you wish you had.

### Today's behavior
Currently is you add a max width the text is extending out of the component.

### The Value Add
Designs where content sits to the right is currently being pushed right based of however long the dropdown need to be, with this enhancement we can decide how we wish to render content verses being subject to the dynamic data. 

Why this should be added/changed in the Design System. Where we could use it. Basically anywhere we have content sitting to the right of a dropdown. Right now the Home team is actively investigating implementing a design like this.

### The Tradeoffs

What we give up or deoptimize to get it. The costs.
The only trade off that I can think of is that on mobile this could cause some spacing concerns so this property should maybe not be available via the mobile phone.

### PR DESCRIPTION
**Pull request by EdwardIrby**
resolves #487

### CODE REVIEW

File: packages/util/src/useCombinedRefs.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import { useRef, useEffect } from 'react'
+
+export const useCombinedRefs = (...refs) => {
+  const targetRef = useRef()
+  useEffect(() => {
+    refs.forEach(ref => {
+      if (!ref) return
+      if (typeof ref === 'function') {
+        ref(targetRef.current)
```
Comment (danethurber) [inline packages/util/src/useCombinedRefs.js]: we probably don't need to support the older ref api. you can decided to leave it in or take it out

Comment (EdwardIrby) [reply packages/util/src/useCombinedRefs.js]: Even though traditional class component callback refs may not be in use there is a new pattern using useCallback that is recommended for [measuring the dom for example ](https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node). I'm going to leave this in place and add a test.
