### PR TITLE
fix(icon): aria-label should update svg attr

### LINKED ISSUE #462: Icon aria-label should be configurable
from @jim-cooper 

| We noticed that the `Icon` doesn't have a title property.  On the course table of contents where we show checkmark icons; for screen readers we'd love to have it say "Module Complete" instead of "Check Icon Image".  Is there a good way to do this currently?

### TODO

add prop to make this configurable

### PR DESCRIPTION
**Pull request by danethurber**
better screen reader support for custom icon labels

fixes #462

### CODE REVIEW

File: packages/icon/src/react/index.js [hunk 1]
```diff
@@ -23,23 +23,22 @@ const style = {
...
 
 class Icon extends React.PureComponent {
-  getIconById(id) {
-    const Comp = icons[id] ? icons[id](React, filterReactProps) : IconNotFound
-    return <Comp />
-  }
-
   render() {
-    const { id, ...props } = this.props
+    const { id, 'aria-label': ariaLabel, ...props } = this.props
```
Comment (jaketrent) [inline packages/icon/src/react/index.js]: rename is needed, right?  (only to get a valid var name)

Comment (danethurber) [reply packages/icon/src/react/index.js]: yeah because `aria-label` isn't a valid var name
