### PR TITLE
fix(position): add yOffset to clipAdjust

### LINKED ISSUE #1048: [site] Dialog and Tooltip docs In-app examples are broken
The tooltip & dialog In-app examples are broken. I suppose it's related to the auto positioning changes.

Dialog
image

Tooltips
image

### PR DESCRIPTION
**Pull request by EdwardIrby**
resolves  #1048

### CODE REVIEW

File: packages/site/pages/components/position.js [hunk 1]
```diff
@@ -180,17 +180,21 @@ function JsExample() {
...
+    setStyle(nextStyle, { bufferWidth: 0 })
+    setHovered(true)
+  }
 
   React.useEffect(() => {
     if (!button.current || !tooltip.current) return
 
     const nextStyle = rightOf(button.current).styleFor(tooltip.current)
-    setStyle(nextStyle)
+    setStyle(nextStyle, { bufferWidth: 0 })
```
Comment (EdwardIrby) [inline packages/site/pages/components/position.js:197]: With the clip in there this example doesn't work as well. I'm still not sure how to improve this custom jsPositioning further it needs to do a better job on initial render
