### PR TITLE
docs(site): fix layout issue with common icon set in Safari

### LINKED ISSUE #951: site: layout issue in Safari with common icons in icon docs
Label is overlapping the icon.

image

### PR DESCRIPTION
**Pull request by sweeting**
Also made the icons 24x24.

Closes #951

### CODE REVIEW

File: packages/site/pages/components/icon.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ const CommonSet = props => (
         const Comp = Icons[id]
         return (
           <div className="icon" key={i}>
-            <Comp size={sizes.large} className="svg" />
+            <Comp size={sizes.medium} className="svg" />
```
Comment (jaketrent) [inline packages/site/pages/components/icon.js]:
```suggestion
            <Comp size={sizes.medium} />
```

Can also remove this (unused).

Comment (sweeting) [reply packages/site/pages/components/icon.js]: @EdwardIrby I used the "Commit suggestion" button in Github to incorporate this feedback from Jake, but then it committed without a commit message and that's what's causing the build failure. Not sure how to fix that.
